### ISSUE TITLE
Submit TX without giving previous block number that contains TX with token UID

### ISSUE THREAD

**Issue by 0xMothman** [omisego/plasma-cash#76]
In your current implementation, if users want to submit a new transaction, they have to specify the previous block number that contains validated TX with token UID. Is there anyway to send a new transaction without specifying the block number? I think we should have a mapping like mapping(uid => latestBlkNum) to keep track the latest validated block containing the TX with token UID.

**Comment by boolafish** [comment]
Hi @0xMothman, 
Thanks for pointing this out. Yes this is a lacking part from our current implementation, which we should improve on.
Currently I'm thinking that client should save those information as in issue #71, which should solve the proble. The reason of doing it in client instead of root chain contract is that people can submit fake/invalid tx for the uid which would lead to invalid latestBlkNum.

**Comment by boolafish** [comment]
@0xMothman do you think #71 looks good enough for you to solve this?

**Comment by 0xMothman** [comment]
Yes, I think your proposal is really good.
